# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
}

DOCUMENTATION = '''
---
module: orion_node
short_description: Created/Removes/Edits Nodes in Solarwinds Orion NPM
description:
    - "Create/Remove Nodes in Orion NPM"
version_added: "2.7"
options:
    hostname:
        description:
            - gpr1tapsws01
        required: true
    username:
        description:
            - admin
        required: true
    password:
        description:
            - admin
        required: true
    state:
        description:
            - The desired state of the node
        required: false
        choices:
            - present
        default:
            - managed
    node_id:
        description:
            - 192.168.1.289, gpr1tapsws01
        required: false
    name:
        description:
            - gpr1tapsws01
        required: false
    ip_address:
        description: 
            - 192.168.1.289
        required: false
    polling_method:
        description:
            - snmp
        default: snmp
        required: false
    ro_community_string:
        description:
            - 55z15z30
        required: false
    snmp_version:
        description:
            - SNMPv2c is used by default
        default: 'snmpv2c'
        requried: false
    snmp_port:
        description:
            - port that SNMP server listens on
        required: false
        default: '161'
    snmp_allow_64:
        description:
            - Set true if device supports 64-bit counters
        type: bool
        default: true
        required: false
    polling_engine:
        description:
            - 10.86.20.92, 10.86.20.91
        required: false

'''


EXAMPLES = '''
---
- name:  Remove a node from Orion
  orion_node:
	hostname: "<Hostname of orion server>"
	username: Orion Username
	password: Orion Password
	name: servername
	state: absent
    
- name: Mute hosts
  hosts: all
  gather_facts: no
  tasks: 
    - orion_node:
        hostname: "{{solarwinds_host}}"
        username: "{{solarwinds_username}}"
        password: "{{solarwinds_password}}"
        name: "{{inventory_hostname}}"
        state: muted       
        unmanage_from: "2020-03-13T20:58:22.033"
        unmanage_until: "2020-03-14T20:58:22.033"
      delegate_to: localhost
'''